#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef PLAYWIRE_SWIFT_H
#define PLAYWIRE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import GoogleMobileAds;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Playwire",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Represents the available corner positions for a floating view.
typedef SWIFT_ENUM(NSInteger, FloatingViewCorner, open) {
  FloatingViewCornerTopLeft = 0,
  FloatingViewCornerTopRight = 1,
  FloatingViewCornerBottomLeft = 2,
  FloatingViewCornerBottomRight = 3,
};

/// Defines the log severity thresholds for the Playwire SDK.
/// Setting a specific level enables that severity and all higher severities above it (e.g., setting <code>.warning</code> will print warnings and errors).
typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
/// Disables all logging completely. No output will be printed to the console.
  LogLevelNone = 0,
/// Logs only critical errors that disrupt normal operations.
  LogLevelError = 1,
/// Logs non-fatal operational warnings and critical errors.
  LogLevelWarning = 2,
/// Logs general information, lifecycle events, warnings, and errors. This enables all log outputs.
  LogLevelInfo = 3,
};

@class PMAdLoader;
@protocol PMAdDelegate;
/// Base protocol representing an ad instance within the SDK.
/// Concrete ad types (e.g. interstitial, fullscreen, banner, VAST)
/// conform to this protocol and may extend it with additional capabilities.
/// <h2>Responsibilities</h2>
/// <ul>
///   <li>
///     Expose the originating loader
///   </li>
///   <li>
///     Expose the underlying ad network
///   </li>
///   <li>
///     Provide lifecycle management (<code>cleanup</code>)
///   </li>
///   <li>
///     Forward interaction events via delegate
///   </li>
/// </ul>
/// <h2>Notes</h2>
/// <ul>
///   <li>
///     All ads are reference types (<code>AnyObject</code>)
///   </li>
///   <li>
///     Delegates are weak by convention (not enforced here)
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire4PMAd_")
@protocol PMAd
/// The loader that created this ad.
@property (nonatomic, readonly, strong) PMAdLoader * _Nonnull adLoader;
/// Delegate receiving ad lifecycle events.
@property (nonatomic, strong) id <PMAdDelegate> _Nullable delegate;
/// Indicates whether the ad contains video content.
@property (nonatomic, readonly) BOOL isVideo;
/// Cleans up resources associated with the ad.
/// Should be called when the ad is no longer needed.
- (void)cleanup;
@end

/// Delegate for receiving ad lifecycle events.
/// Implement this protocol to be notified about user interaction
/// and impression tracking for ads.
/// These callbacks are triggered by the SDK when relevant events occur.
SWIFT_PROTOCOL("_TtP8Playwire12PMAdDelegate_")
@protocol PMAdDelegate
/// Called when the ad has been successfully displayed (impression recorded).
/// \param ad The ad instance that was impressed
///
- (void)adImpressedWithAd:(id <PMAd> _Nonnull)ad;
/// Called when the user clicks on the ad.
/// \param ad The ad instance that was clicked
///
- (void)adClickedWithAd:(id <PMAd> _Nonnull)ad;
@end

SWIFT_CLASS("_TtC8Playwire10PMAdLoader")
@interface PMAdLoader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PWAdViewPresenter;
@protocol PMBannerAd;
/// Delegate notified when the banner managed by <code>PWAdViewPresenter</code> changes.
/// This includes both initial load and subsequent refreshes or removals.
SWIFT_PROTOCOL("_TtP8Playwire25PMAdViewPresenterDelegate_")
@protocol PMAdViewPresenterDelegate
/// Called whenever the current banner changes.
/// \param presenter The presenter managing the banner lifecycle.
///
/// \param oldBanner The previously displayed banner, if any.
///
/// \param newBanner The newly available banner, if any.
///
- (void)didChangeAdPresenterBannerWithPresenter:(PWAdViewPresenter * _Nonnull)presenter oldBanner:(id <PMBannerAd> _Nullable)oldBanner newBanner:(id <PMBannerAd> _Nullable)newBanner;
@end

@class UIView;
/// Represents a banner ad.
/// Banner ads differ from full-screen formats in that they:
/// <ul>
///   <li>
///     Are embedded within the UI
///   </li>
///   <li>
///     Manage their own view lifecycle
///   </li>
///   <li>
///     May react to layout or context changes
///   </li>
/// </ul>
/// <h2>Responsibilities</h2>
/// <ul>
///   <li>
///     Provide a <code>UIView</code> representation for rendering
///   </li>
///   <li>
///     Handle context/lifecycle changes (e.g. screen transitions, resizing)
///   </li>
///   <li>
///     Forward media lifecycle events (e.g. video completion)
///   </li>
/// </ul>
/// <h2>Notes</h2>
/// <ul>
///   <li>
///     The returned view from <code>createUIView()</code> is owned by the SDK
///     unless otherwise documented by the implementation.
///   </li>
///   <li>
///     Delegate should be weakly held by implementations.
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire10PMBannerAd_")
@protocol PMBannerAd <PMAd>
/// Creates and returns the view used to render the banner.
///
/// returns:
/// A configured <code>UIView</code> ready to be added to the view hierarchy
- (UIView * _Nonnull)createUIView SWIFT_WARN_UNUSED_RESULT;
/// Notifies the banner that a context change is about to occur.
/// This can include:
/// <ul>
///   <li>
///     view controller transitions
///   </li>
///   <li>
///     layout changes
///   </li>
///   <li>
///     visibility changes
///   </li>
/// </ul>
- (void)willStartContextChange;
/// Notifies the banner that a context change has completed.
- (void)didEndContextChange;
@end

SWIFT_PROTOCOL("_TtP8Playwire18PMBannerAdDelegate_")
@protocol PMBannerAdDelegate <PMAdDelegate>
/// Called when the banner finishes playing its media content.
/// This is typically relevant for:
/// <ul>
///   <li>
///     video banners
///   </li>
///   <li>
///     rich media creatives
///   </li>
/// </ul>
/// \param banner The banner ad instance
///
- (void)bannerAdFinishedPlayingWithBanner:(id <PMBannerAd> _Nonnull)banner;
@end

SWIFT_CLASS("_TtC8Playwire16PMBannerAdLoader")
@interface PMBannerAdLoader : PMAdLoader
/// Starts banner loading and stores the completion for future refreshes.
/// \param onAdResult Completion returning the loaded banner,
/// or <code>nil</code> when no banner is available
///
- (void)loadOnAdResult:(void (^ _Nonnull)(id <PMBannerAd> _Nullable))onAdResult;
/// Requests a manual banner refresh.
/// Actual execution is subject to refresh timing and count limits.
- (void)refresh;
/// Called when the banner records an impression.
/// Non-video banners schedule the next automatic load immediately after impression.
- (void)adImpressedWithAd:(id <PMAd> _Nonnull)ad;
@end

@class UIViewController;
SWIFT_PROTOCOL("_TtP8Playwire14PMFullScreenAd_")
@protocol PMFullScreenAd <PMAd>
/// Presents the ad from the provided view controller.
/// \param vc The presenting view controller
///
- (void)showFrom:(UIViewController * _Nonnull)vc;
@end

SWIFT_PROTOCOL("_TtP8Playwire22PMFullScreenAdDelegate_")
@protocol PMFullScreenAdDelegate <PMAdDelegate>
/// Called after the full-screen ad has been presented.
/// \param fullScreen The presented full-screen ad
///
- (void)fullScreeenAdPresentedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
/// Called just before the full-screen ad is dismissed.
/// \param fullScreen The full-screen ad being closed
///
- (void)fullScreenAdWillCloseWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
/// Called after the full-screen ad has been dismissed.
/// \param fullScreen The full-screen ad that was closed
///
- (void)fullScreenAdClosedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
@end

/// Represents an interstitial ad.
/// This protocol specializes <code>PMFullScreenAd</code> without adding new
/// requirements, allowing interstitial ads to be treated distinctly
/// from other full-screen formats (e.g. rewarded, VAST).
/// <h2>Responsibilities</h2>
/// <ul>
///   <li>
///     Present a full-screen ad via <code>show(from:)</code>
///   </li>
///   <li>
///     Participate in full-screen lifecycle events
///   </li>
///   <li>
///     Integrate with delegate-based callbacks
///   </li>
/// </ul>
/// <h2>Notes</h2>
/// <ul>
///   <li>
///     Acts as a semantic type, not a behavioral extension (for now)
///   </li>
///   <li>
///     Future interstitial-specific APIs can be added here without
///     impacting other full-screen ad types
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire16PMInterstitialAd_")
@protocol PMInterstitialAd <PMFullScreenAd>
@end

/// Delegate for interstitial ad lifecycle events.
/// This protocol does not introduce new methods beyond
/// <code>PMFullScreenAdDelegate</code>, but provides a semantic specialization
/// for interstitial ads.
/// <h2>Purpose</h2>
/// <ul>
///   <li>
///     Allows type-safe differentiation between ad formats
///   </li>
///   <li>
///     Enables future extension with interstitial-specific callbacks
///   </li>
///   <li>
///     Improves clarity in publisher integrations
///   </li>
/// </ul>
/// <h2>Inherits</h2>
/// <ul>
///   <li>
///     <code>PMAdDelegate</code>
///   </li>
///   <li>
///     <code>PMFullScreenAdDelegate</code>
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire24PMInterstitialAdDelegate_")
@protocol PMInterstitialAdDelegate <PMFullScreenAdDelegate>
@end

SWIFT_CLASS("_TtC8Playwire22PMInterstitialAdLoader")
@interface PMInterstitialAdLoader : PMAdLoader
/// Loads an interstitial ad.
/// \param onAdResult Completion returning the loaded interstitial,
/// or <code>nil</code> if loading failed
///
- (void)loadOnAdResult:(void (^ _Nonnull)(id <PMInterstitialAd> _Nullable))onAdResult;
@end

@class NSString;
SWIFT_CLASS("_TtC8Playwire11PMTargeting")
@interface PMTargeting : NSObject
/// Current targeting values.
/// Returns a thread-safe snapshot of all targeting entries.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull targeting;
/// Removes all targeting values.
- (void)clear;
/// Adds or updates targeting values.
/// Existing keys are overwritten by the new values.
/// \param targets Dictionary of targeting entries to merge.
///
- (void)add:(NSDictionary<NSString *, NSString *> * _Nullable)targets;
/// Removes targeting values for the given keys.
/// \param keys Keys to remove from the targeting store.
///
- (void)remove:(NSArray<NSString *> * _Nullable)keys;
/// Sets a client tag at a specific index.
/// The resulting targeting key is:
/// <code>cust_cli_tag_<index></code>
/// \param clientTag Client tag value
///
/// \param index Tag index
///
- (void)setClientTag:(NSString * _Nonnull)clientTag at:(NSInteger)index;
/// Removes the client tag stored at a specific index.
/// \param index Tag index
///
- (void)removeClientTagAt:(NSInteger)index;
/// Sets multiple client tags using 1-based indexing.
/// Tags are mapped as:
/// <ul>
///   <li>
///     first item  -> <code>cust_cli_tag_1</code>
///   </li>
///   <li>
///     second item -> <code>cust_cli_tag_2</code>
///   </li>
///   <li>
///     etc.
///   </li>
/// </ul>
/// Empty strings remove the corresponding tag.
/// \param clientTags Ordered list of client tags
///
- (void)setClientTags:(NSArray<NSString *> * _Nonnull)clientTags;
/// Sets app categories as a comma-separated targeting value.
/// Example:
/// <code>["sports", "gaming"]</code> → <code>"sports,gaming"</code>
/// \param categories List of categories to associate with the request
///
- (void)setAppCategories:(NSArray<NSString *> * _Nullable)categories;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum PWAdErrorCode : NSInteger;
SWIFT_CLASS("_TtC8Playwire9PWAdError")
@interface PWAdError : NSObject
@property (nonatomic, readonly) enum PWAdErrorCode code;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull metadata;
- (nonnull instancetype)initWithCode:(enum PWAdErrorCode)code metadata:(NSDictionary<NSString *, id> * _Nonnull)metadata OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PWAdErrorCode, open) {
  PWAdErrorCodeUnknown = 1000,
  PWAdErrorCodeNoFill = 1001,
  PWAdErrorCodeInvalidRequest = 1002,
  PWAdErrorCodeNetworkError = 1003,
  PWAdErrorCodeTimeout = 1004,
  PWAdErrorCodeServerError = 1005,
  PWAdErrorCodeInternalError = 1006,
  PWAdErrorCodeDisplayError = 1007,
  PWAdErrorCodeMediationError = 1008,
  PWAdErrorCodePreconditionFailed = 1009,
};

SWIFT_CLASS("_TtC8Playwire17PWAdLoaderBuilder")
@interface PWAdLoaderBuilder : NSObject
/// Creates a builder for a specific ad unit.
/// \param adUnitName Identifier of the ad unit
///
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName OBJC_DESIGNATED_INITIALIZER;
/// Sets the view controller used for ad presentation.
/// Required for full-screen formats and certain network integrations.
/// \param viewController Presenting view controller
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withViewController:(UIViewController * _Nonnull)viewController;
/// Sets the simulated success rate for ad loading.
/// \param successRate Value between <code>0.0</code> and <code>1.0</code>
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withSuccessRate:(double)successRate;
/// Enables or disables mock mode.
/// When enabled, the loader will use mock ads instead of real network requests.
/// \param mock Whether to enable mock mode
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withMock:(BOOL)mock;
/// Sets the targeting information for the ad request.
/// \param targeting Targeting information associated with the ad request
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withTargeting:(PMTargeting * _Nonnull)targeting;
/// Builds a banner ad loader.
/// A snapshot of the current configuration is taken at build time.
///
/// returns:
/// A configured <code>PMBannerAdLoader</code>
- (PMBannerAdLoader * _Nonnull)buildBannerAdLoader SWIFT_WARN_UNUSED_RESULT;
/// Builds an interstitial ad loader.
/// A snapshot of the current configuration is taken at build time.
///
/// returns:
/// A configured <code>PMInterstitialAdLoader</code>
- (PMInterstitialAdLoader * _Nonnull)buildInterstitialAdLoader SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Responsible for loading, managing, and presenting banner ads.
/// <code>PWAdViewPresenter</code>:
/// <ul>
///   <li>
///     interacts with a <code>PMBannerAdLoader</code>
///   </li>
///   <li>
///     maintains the currently active banner
///   </li>
///   <li>
///     handles attaching/detaching the banner view from a container
///   </li>
///   <li>
///     notifies both a delegate and the container about lifecycle events
///   </li>
/// </ul>
/// This class is intended to be the core building block for banner presentation logic.
SWIFT_CLASS("_TtC8Playwire17PWAdViewPresenter")
@interface PWAdViewPresenter : NSObject
/// Delegate que será notificado cuando cambie el banner actual.
@property (nonatomic, weak) id <PMAdViewPresenterDelegate> _Nullable delegate;
/// Convenience initializer that builds a banner loader internally.
/// \param adUnitName The ad unit identifier.
///
/// \param controller The view controller used for ad loading context.
///
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nonnull)controller;
/// Initializes the presenter with a preconfigured banner loader.
/// Automatically starts loading a banner. Each load result updates
/// the internal state and presentation.
/// \param bannerLoader The loader used to fetch banners.
///
- (nonnull instancetype)initWithBannerLoader:(PMBannerAdLoader * _Nonnull)bannerLoader OBJC_DESIGNATED_INITIALIZER;
/// The view that will host the banner.
/// When changed, the presenter automatically moves the banner view
/// between containers and triggers lifecycle callbacks.
/// If both old and new holders are non-nil, a context change is triggered.
@property (nonatomic, strong) UIView * _Nullable bannerHolder;
/// Cleans up the current banner and releases resources.
/// This:
/// <ul>
///   <li>
///     calls <code>cleanup()</code> on the banner
///   </li>
///   <li>
///     removes it from the container
///   </li>
///   <li>
///     clears internal references
///   </li>
/// </ul>
- (void)cleanup;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PWTargeting;
@protocol PWFullScreenAdDelegate;
@class PWLoadParams;
SWIFT_CLASS("_TtC8Playwire14PWFullScreenAd")
@interface PWFullScreenAd : NSObject
@property (nonatomic, strong) PWTargeting * _Nonnull targeting;
@property (nonatomic, readonly) BOOL isLoaded;
@property (nonatomic, weak) id <PWFullScreenAdDelegate> _Nullable delegate;
- (void)load;
- (void)loadWithParams:(PWLoadParams * _Nonnull)params;
- (void)show;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8Playwire11PWAppOpenAd")
@interface PWAppOpenAd : PWFullScreenAd
@property (nonatomic) BOOL autoReloadOnExpiration;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName viewController:(UIViewController * _Nonnull)viewController delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)show;
@end

@protocol PWViewAdDelegate;
@class NSCoder;
SWIFT_CLASS("_TtC8Playwire8PWViewAd")
@interface PWViewAd : UIView
@property (nonatomic, copy) NSString * _Nullable adUnitName;
@property (nonatomic) BOOL autoload;
@property (nonatomic, weak) id <PWViewAdDelegate> _Nullable delegate;
@property (nonatomic, readonly, strong) PWTargeting * _Nonnull targeting;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWViewAdDelegate> _Nullable)delegate;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nullable)controller;
- (void)awakeFromNib;
- (void)destroy;
- (void)load;
- (void)loadWithParams:(PWLoadParams * _Nonnull)params;
@property (nonatomic, readonly) BOOL isLoaded;
- (void)refresh;
@end

SWIFT_CLASS("_TtC8Playwire12PWBannerView")
@interface PWBannerView : PWViewAd
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class GADAdLoader;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
@end

@class GADNativeAd;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
@end

@class NSValue;
@class GAMBannerView;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GAMBannerAdLoaderDelegate>
- (NSArray<NSValue *> * _Nonnull)validBannerSizesForAdLoader:(GADAdLoader * _Nonnull)adLoader SWIFT_WARN_UNUSED_RESULT;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveGAMBannerView:(GAMBannerView * _Nonnull)bannerView;
@end

@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADNativeAdDelegate>
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdIsMuted:(GADNativeAd * _Nonnull)nativeAd;
@end

@class GADBannerView;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADBannerViewDelegate>
- (void)bannerViewDidReceiveAd:(GADBannerView * _Nonnull)bannerView;
- (void)bannerView:(GADBannerView * _Nonnull)bannerView didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidRecordClick:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(GADBannerView * _Nonnull)bannerView;
@end

typedef SWIFT_ENUM(NSInteger, PWCMPType, open) {
  PWCMPTypeNone = 0,
  PWCMPTypeAlreadyLaunched = 1,
  PWCMPTypeGoogleUmp = 2,
};

@protocol PWFloatingBannerAnimationHandler;
@class PWFloatingView;
SWIFT_CLASS("_TtC8Playwire16PWFloatingBanner")
@interface PWFloatingBanner : NSObject <PMAdViewPresenterDelegate>
@property (nonatomic, weak) id <PWFloatingBannerAnimationHandler> _Nullable animationHandler;
@property (nonatomic) enum FloatingViewCorner preferredCorner;
@property (nonatomic, strong) UIView * _Nullable inlineView;
- (nonnull instancetype)initWithPresenter:(PWAdViewPresenter * _Nonnull)presenter floatingView:(PWFloatingView * _Nonnull)floatingView OBJC_DESIGNATED_INITIALIZER;
- (void)didChangeAdPresenterBannerWithPresenter:(PWAdViewPresenter * _Nonnull)presenter oldBanner:(id <PMBannerAd> _Nullable)oldBanner newBanner:(id <PMBannerAd> _Nullable)newBanner;
- (void)cleanup;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP8Playwire32PWFloatingBannerAnimationHandler_")
@protocol PWFloatingBannerAnimationHandler
- (void)performAnimationWithBlock:(void (^ _Nonnull)(void))block completion:(void (^ _Nullable)(void))completion;
@end

@class UIGestureRecognizer;
/// A draggable floating view that can snap to predefined screen corners.
/// <code>PWFloatingView</code> is designed to be superimposed on top of a view controller’s
/// view and supports two main layout modes:
/// <ul>
///   <li>
///     <em>Cornered mode</em>: the view is positioned in one of the screen corners and can be dragged.
///   </li>
///   <li>
///     <em>Superimposed mode</em>: the view fills a target view and dragging is disabled.
///   </li>
/// </ul>
/// When dragging ends, the view automatically snaps to the nearest corner.
/// The view respects safe area insets and configurable margins when computing
/// valid positions.
SWIFT_CLASS("_TtC8Playwire14PWFloatingView")
@interface PWFloatingView : UIView <UIGestureRecognizerDelegate>
/// Margins applied when positioning the view in cornered mode.
@property (nonatomic) UIEdgeInsets corneredMargins;
/// Size used when the view is in cornered mode.
@property (nonatomic) CGSize corneredSize;
/// Not supported. Must be initialized programmatically.
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Initializes a floating view attached to a view controller.
/// During initialization:
/// <ul>
///   <li>
///     the view is added to the controller’s root view
///   </li>
///   <li>
///     a pan gesture recognizer is configured
///   </li>
///   <li>
///     an initial layout reset is performed
///   </li>
/// </ul>
/// \param controller The view controller that will host the floating view.
///
- (nonnull instancetype)initWithController:(UIViewController * _Nonnull)controller OBJC_DESIGNATED_INITIALIZER;
/// Allows simultaneous recognition with other gestures.
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
/// Expands the view to match the frame of a target view.
/// Disables dragging behavior.
/// \param targetView The view to overlay.
///
- (void)layoutSuperimposedTo:(UIView * _Nonnull)targetView;
/// Positions the view in the default corner (<code>.bottomRight</code>).
- (void)layoutCornered;
/// Positions the view in the default corner (<code>.bottomRight</code>).
- (void)resetLayout;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_PROTOCOL("_TtP8Playwire22PWFullScreenAdDelegate_")
@protocol PWFullScreenAdDelegate
- (void)fullScreenAdDidLoad:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidFailToLoad:(PWFullScreenAd * _Nonnull)ad error:(PWAdError * _Nonnull)error;
- (void)fullScreenAdWillPresentFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdWillDismissFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidDismissFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidFailToPresentFullScreenContent:(PWFullScreenAd * _Nonnull)ad error:(PWAdError * _Nonnull)error;
- (void)fullScreenAdDidRecordImpression:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidRecordClick:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidUserEarn:(PWFullScreenAd * _Nonnull)ad type:(NSString * _Nonnull)type amount:(double)amount;
@end

SWIFT_CLASS("_TtC8Playwire14PWInterstitial")
@interface PWInterstitial : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName viewController:(UIViewController * _Nonnull)viewController delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)show;
@end

@interface PWInterstitial (SWIFT_EXTENSION(Playwire)) <PMInterstitialAdDelegate>
- (void)adImpressedWithAd:(id <PMAd> _Nonnull)ad;
- (void)adClickedWithAd:(id <PMAd> _Nonnull)ad;
- (void)fullScreenAdClosedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
- (void)fullScreenAdWillCloseWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
- (void)fullScreeenAdPresentedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
@end

SWIFT_CLASS("_TtC8Playwire12PWLoadParams")
@interface PWLoadParams : NSObject
- (PWLoadParams * _Nonnull)withTargeting:(NSDictionary<NSString *, NSString *> * _Nonnull)targeting;
- (PWLoadParams * _Nonnull)withWidth:(CGFloat)width;
- (PWLoadParams * _Nonnull)withDeviceOrientation:(UIInterfaceOrientation)orientation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8Playwire12PWNativeView")
@interface PWNativeView : PWViewAd
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface PWNativeView (SWIFT_EXTENSION(Playwire)) <GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
@end

@interface PWNativeView (SWIFT_EXTENSION(Playwire)) <GADNativeAdDelegate>
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdIsMuted:(GADNativeAd * _Nonnull)nativeAd;
@end

SWIFT_CLASS("_TtC8Playwire10PWRewarded")
@interface PWRewarded : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName viewController:(UIViewController * _Nonnull)viewController delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)show;
@end

SWIFT_CLASS("_TtC8Playwire11PWTargeting")
@interface PWTargeting : NSObject
- (PWTargeting * _Nonnull)clear SWIFT_WARN_UNUSED_RESULT;
- (PWTargeting * _Nonnull)add:(NSDictionary<NSString *, NSString *> * _Nullable)targets;
- (PWTargeting * _Nonnull)remove:(NSArray<NSString *> * _Nullable)keys;
- (PWTargeting * _Nonnull)setClientTag:(NSString * _Nonnull)clientTag at:(NSInteger)index;
- (PWTargeting * _Nonnull)removeClientTagAt:(NSInteger)index;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP8Playwire16PWViewAdDelegate_")
@protocol PWViewAdDelegate
- (void)viewAdDidLoad:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidFailToLoad:(PWViewAd * _Nonnull)ad error:(PWAdError * _Nonnull)error;
- (void)viewAdWillPresentFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdWillDismissFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidDismissFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidRecordImpression:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidRecordClick:(PWViewAd * _Nonnull)ad;
@end

@class GAMRequest;
SWIFT_CLASS("_TtC8Playwire11PlaywireSDK")
@interface PlaywireSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaywireSDK * _Nonnull shared;)
+ (PlaywireSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum LogLevel logLevel;
@property (nonatomic, readonly, strong) PWTargeting * _Nonnull targeting;
@property (nonatomic) BOOL test;
@property (nonatomic) enum PWCMPType cmp;
- (void)startWithPublisherId:(NSString * _Nonnull)publisherId appId:(NSString * _Nonnull)appId viewController:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
- (void)initializeWithPublisherId:(NSString * _Nonnull)publisherId appId:(NSString * _Nonnull)appId viewController:(UIViewController * _Nonnull)viewController completionHandler:(void (^ _Nonnull)(void))completionHandler SWIFT_DEPRECATED_MSG("This method silently fails on error. Please migrate to 'start' to properly handle SDK initialization failures.");
@property (nonatomic) BOOL isMuted;
- (void)configureWithRequest:(GAMRequest * _Nonnull)request;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.2.4 effective-5.10 (swiftlang-6.2.4.1.4 clang-1700.6.4.2)
#ifndef PLAYWIRE_SWIFT_H
#define PLAYWIRE_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import GoogleMobileAds;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="Playwire",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

/// Represents the available corner positions for a floating view.
typedef SWIFT_ENUM(NSInteger, FloatingViewCorner, open) {
  FloatingViewCornerTopLeft = 0,
  FloatingViewCornerTopRight = 1,
  FloatingViewCornerBottomLeft = 2,
  FloatingViewCornerBottomRight = 3,
};

/// Defines the log severity thresholds for the Playwire SDK.
/// Setting a specific level enables that severity and all higher severities above it (e.g., setting <code>.warning</code> will print warnings and errors).
typedef SWIFT_ENUM(NSInteger, LogLevel, open) {
/// Disables all logging completely. No output will be printed to the console.
  LogLevelNone = 0,
/// Logs only critical errors that disrupt normal operations.
  LogLevelError = 1,
/// Logs non-fatal operational warnings and critical errors.
  LogLevelWarning = 2,
/// Logs general information, lifecycle events, warnings, and errors. This enables all log outputs.
  LogLevelInfo = 3,
};

@class PMAdLoader;
@protocol PMAdDelegate;
/// Base protocol representing an ad instance within the SDK.
/// Concrete ad types (e.g. interstitial, fullscreen, banner, VAST)
/// conform to this protocol and may extend it with additional capabilities.
/// <h2>Responsibilities</h2>
/// <ul>
///   <li>
///     Expose the originating loader
///   </li>
///   <li>
///     Expose the underlying ad network
///   </li>
///   <li>
///     Provide lifecycle management (<code>cleanup</code>)
///   </li>
///   <li>
///     Forward interaction events via delegate
///   </li>
/// </ul>
/// <h2>Notes</h2>
/// <ul>
///   <li>
///     All ads are reference types (<code>AnyObject</code>)
///   </li>
///   <li>
///     Delegates are weak by convention (not enforced here)
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire4PMAd_")
@protocol PMAd
/// The loader that created this ad.
@property (nonatomic, readonly, strong) PMAdLoader * _Nonnull adLoader;
/// Delegate receiving ad lifecycle events.
@property (nonatomic, strong) id <PMAdDelegate> _Nullable delegate;
/// Indicates whether the ad contains video content.
@property (nonatomic, readonly) BOOL isVideo;
/// Cleans up resources associated with the ad.
/// Should be called when the ad is no longer needed.
- (void)cleanup;
@end

/// Delegate for receiving ad lifecycle events.
/// Implement this protocol to be notified about user interaction
/// and impression tracking for ads.
/// These callbacks are triggered by the SDK when relevant events occur.
SWIFT_PROTOCOL("_TtP8Playwire12PMAdDelegate_")
@protocol PMAdDelegate
/// Called when the ad has been successfully displayed (impression recorded).
/// \param ad The ad instance that was impressed
///
- (void)adImpressedWithAd:(id <PMAd> _Nonnull)ad;
/// Called when the user clicks on the ad.
/// \param ad The ad instance that was clicked
///
- (void)adClickedWithAd:(id <PMAd> _Nonnull)ad;
@end

SWIFT_CLASS("_TtC8Playwire10PMAdLoader")
@interface PMAdLoader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PWAdViewPresenter;
@protocol PMBannerAd;
/// Delegate notified when the banner managed by <code>PWAdViewPresenter</code> changes.
/// This includes both initial load and subsequent refreshes or removals.
SWIFT_PROTOCOL("_TtP8Playwire25PMAdViewPresenterDelegate_")
@protocol PMAdViewPresenterDelegate
/// Called whenever the current banner changes.
/// \param presenter The presenter managing the banner lifecycle.
///
/// \param oldBanner The previously displayed banner, if any.
///
/// \param newBanner The newly available banner, if any.
///
- (void)didChangeAdPresenterBannerWithPresenter:(PWAdViewPresenter * _Nonnull)presenter oldBanner:(id <PMBannerAd> _Nullable)oldBanner newBanner:(id <PMBannerAd> _Nullable)newBanner;
@end

@class UIView;
/// Represents a banner ad.
/// Banner ads differ from full-screen formats in that they:
/// <ul>
///   <li>
///     Are embedded within the UI
///   </li>
///   <li>
///     Manage their own view lifecycle
///   </li>
///   <li>
///     May react to layout or context changes
///   </li>
/// </ul>
/// <h2>Responsibilities</h2>
/// <ul>
///   <li>
///     Provide a <code>UIView</code> representation for rendering
///   </li>
///   <li>
///     Handle context/lifecycle changes (e.g. screen transitions, resizing)
///   </li>
///   <li>
///     Forward media lifecycle events (e.g. video completion)
///   </li>
/// </ul>
/// <h2>Notes</h2>
/// <ul>
///   <li>
///     The returned view from <code>createUIView()</code> is owned by the SDK
///     unless otherwise documented by the implementation.
///   </li>
///   <li>
///     Delegate should be weakly held by implementations.
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire10PMBannerAd_")
@protocol PMBannerAd <PMAd>
/// Creates and returns the view used to render the banner.
///
/// returns:
/// A configured <code>UIView</code> ready to be added to the view hierarchy
- (UIView * _Nonnull)createUIView SWIFT_WARN_UNUSED_RESULT;
/// Notifies the banner that a context change is about to occur.
/// This can include:
/// <ul>
///   <li>
///     view controller transitions
///   </li>
///   <li>
///     layout changes
///   </li>
///   <li>
///     visibility changes
///   </li>
/// </ul>
- (void)willStartContextChange;
/// Notifies the banner that a context change has completed.
- (void)didEndContextChange;
@end

SWIFT_PROTOCOL("_TtP8Playwire18PMBannerAdDelegate_")
@protocol PMBannerAdDelegate <PMAdDelegate>
/// Called when the banner finishes playing its media content.
/// This is typically relevant for:
/// <ul>
///   <li>
///     video banners
///   </li>
///   <li>
///     rich media creatives
///   </li>
/// </ul>
/// \param banner The banner ad instance
///
- (void)bannerAdFinishedPlayingWithBanner:(id <PMBannerAd> _Nonnull)banner;
@end

SWIFT_CLASS("_TtC8Playwire16PMBannerAdLoader")
@interface PMBannerAdLoader : PMAdLoader
/// Starts banner loading and stores the completion for future refreshes.
/// \param onAdResult Completion returning the loaded banner,
/// or <code>nil</code> when no banner is available
///
- (void)loadOnAdResult:(void (^ _Nonnull)(id <PMBannerAd> _Nullable))onAdResult;
/// Requests a manual banner refresh.
/// Actual execution is subject to refresh timing and count limits.
- (void)refresh;
/// Called when the banner records an impression.
/// Non-video banners schedule the next automatic load immediately after impression.
- (void)adImpressedWithAd:(id <PMAd> _Nonnull)ad;
@end

@class UIViewController;
SWIFT_PROTOCOL("_TtP8Playwire14PMFullScreenAd_")
@protocol PMFullScreenAd <PMAd>
/// Presents the ad from the provided view controller.
/// \param vc The presenting view controller
///
- (void)showFrom:(UIViewController * _Nonnull)vc;
@end

SWIFT_PROTOCOL("_TtP8Playwire22PMFullScreenAdDelegate_")
@protocol PMFullScreenAdDelegate <PMAdDelegate>
/// Called after the full-screen ad has been presented.
/// \param fullScreen The presented full-screen ad
///
- (void)fullScreeenAdPresentedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
/// Called just before the full-screen ad is dismissed.
/// \param fullScreen The full-screen ad being closed
///
- (void)fullScreenAdWillCloseWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
/// Called after the full-screen ad has been dismissed.
/// \param fullScreen The full-screen ad that was closed
///
- (void)fullScreenAdClosedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
@end

/// Represents an interstitial ad.
/// This protocol specializes <code>PMFullScreenAd</code> without adding new
/// requirements, allowing interstitial ads to be treated distinctly
/// from other full-screen formats (e.g. rewarded, VAST).
/// <h2>Responsibilities</h2>
/// <ul>
///   <li>
///     Present a full-screen ad via <code>show(from:)</code>
///   </li>
///   <li>
///     Participate in full-screen lifecycle events
///   </li>
///   <li>
///     Integrate with delegate-based callbacks
///   </li>
/// </ul>
/// <h2>Notes</h2>
/// <ul>
///   <li>
///     Acts as a semantic type, not a behavioral extension (for now)
///   </li>
///   <li>
///     Future interstitial-specific APIs can be added here without
///     impacting other full-screen ad types
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire16PMInterstitialAd_")
@protocol PMInterstitialAd <PMFullScreenAd>
@end

/// Delegate for interstitial ad lifecycle events.
/// This protocol does not introduce new methods beyond
/// <code>PMFullScreenAdDelegate</code>, but provides a semantic specialization
/// for interstitial ads.
/// <h2>Purpose</h2>
/// <ul>
///   <li>
///     Allows type-safe differentiation between ad formats
///   </li>
///   <li>
///     Enables future extension with interstitial-specific callbacks
///   </li>
///   <li>
///     Improves clarity in publisher integrations
///   </li>
/// </ul>
/// <h2>Inherits</h2>
/// <ul>
///   <li>
///     <code>PMAdDelegate</code>
///   </li>
///   <li>
///     <code>PMFullScreenAdDelegate</code>
///   </li>
/// </ul>
SWIFT_PROTOCOL("_TtP8Playwire24PMInterstitialAdDelegate_")
@protocol PMInterstitialAdDelegate <PMFullScreenAdDelegate>
@end

SWIFT_CLASS("_TtC8Playwire22PMInterstitialAdLoader")
@interface PMInterstitialAdLoader : PMAdLoader
/// Loads an interstitial ad.
/// \param onAdResult Completion returning the loaded interstitial,
/// or <code>nil</code> if loading failed
///
- (void)loadOnAdResult:(void (^ _Nonnull)(id <PMInterstitialAd> _Nullable))onAdResult;
@end

@class NSString;
SWIFT_CLASS("_TtC8Playwire11PMTargeting")
@interface PMTargeting : NSObject
/// Current targeting values.
/// Returns a thread-safe snapshot of all targeting entries.
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSString *> * _Nonnull targeting;
/// Removes all targeting values.
- (void)clear;
/// Adds or updates targeting values.
/// Existing keys are overwritten by the new values.
/// \param targets Dictionary of targeting entries to merge.
///
- (void)add:(NSDictionary<NSString *, NSString *> * _Nullable)targets;
/// Removes targeting values for the given keys.
/// \param keys Keys to remove from the targeting store.
///
- (void)remove:(NSArray<NSString *> * _Nullable)keys;
/// Sets a client tag at a specific index.
/// The resulting targeting key is:
/// <code>cust_cli_tag_<index></code>
/// \param clientTag Client tag value
///
/// \param index Tag index
///
- (void)setClientTag:(NSString * _Nonnull)clientTag at:(NSInteger)index;
/// Removes the client tag stored at a specific index.
/// \param index Tag index
///
- (void)removeClientTagAt:(NSInteger)index;
/// Sets multiple client tags using 1-based indexing.
/// Tags are mapped as:
/// <ul>
///   <li>
///     first item  -> <code>cust_cli_tag_1</code>
///   </li>
///   <li>
///     second item -> <code>cust_cli_tag_2</code>
///   </li>
///   <li>
///     etc.
///   </li>
/// </ul>
/// Empty strings remove the corresponding tag.
/// \param clientTags Ordered list of client tags
///
- (void)setClientTags:(NSArray<NSString *> * _Nonnull)clientTags;
/// Sets app categories as a comma-separated targeting value.
/// Example:
/// <code>["sports", "gaming"]</code> → <code>"sports,gaming"</code>
/// \param categories List of categories to associate with the request
///
- (void)setAppCategories:(NSArray<NSString *> * _Nullable)categories;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum PWAdErrorCode : NSInteger;
SWIFT_CLASS("_TtC8Playwire9PWAdError")
@interface PWAdError : NSObject
@property (nonatomic, readonly) enum PWAdErrorCode code;
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSString * _Nonnull message;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull metadata;
- (nonnull instancetype)initWithCode:(enum PWAdErrorCode)code metadata:(NSDictionary<NSString *, id> * _Nonnull)metadata OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(NSInteger, PWAdErrorCode, open) {
  PWAdErrorCodeUnknown = 1000,
  PWAdErrorCodeNoFill = 1001,
  PWAdErrorCodeInvalidRequest = 1002,
  PWAdErrorCodeNetworkError = 1003,
  PWAdErrorCodeTimeout = 1004,
  PWAdErrorCodeServerError = 1005,
  PWAdErrorCodeInternalError = 1006,
  PWAdErrorCodeDisplayError = 1007,
  PWAdErrorCodeMediationError = 1008,
  PWAdErrorCodePreconditionFailed = 1009,
};

SWIFT_CLASS("_TtC8Playwire17PWAdLoaderBuilder")
@interface PWAdLoaderBuilder : NSObject
/// Creates a builder for a specific ad unit.
/// \param adUnitName Identifier of the ad unit
///
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName OBJC_DESIGNATED_INITIALIZER;
/// Sets the view controller used for ad presentation.
/// Required for full-screen formats and certain network integrations.
/// \param viewController Presenting view controller
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withViewController:(UIViewController * _Nonnull)viewController;
/// Sets the simulated success rate for ad loading.
/// \param successRate Value between <code>0.0</code> and <code>1.0</code>
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withSuccessRate:(double)successRate;
/// Enables or disables mock mode.
/// When enabled, the loader will use mock ads instead of real network requests.
/// \param mock Whether to enable mock mode
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withMock:(BOOL)mock;
/// Sets the targeting information for the ad request.
/// \param targeting Targeting information associated with the ad request
///
///
/// returns:
/// The builder instance for chaining
- (PWAdLoaderBuilder * _Nonnull)withTargeting:(PMTargeting * _Nonnull)targeting;
/// Builds a banner ad loader.
/// A snapshot of the current configuration is taken at build time.
///
/// returns:
/// A configured <code>PMBannerAdLoader</code>
- (PMBannerAdLoader * _Nonnull)buildBannerAdLoader SWIFT_WARN_UNUSED_RESULT;
/// Builds an interstitial ad loader.
/// A snapshot of the current configuration is taken at build time.
///
/// returns:
/// A configured <code>PMInterstitialAdLoader</code>
- (PMInterstitialAdLoader * _Nonnull)buildInterstitialAdLoader SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Responsible for loading, managing, and presenting banner ads.
/// <code>PWAdViewPresenter</code>:
/// <ul>
///   <li>
///     interacts with a <code>PMBannerAdLoader</code>
///   </li>
///   <li>
///     maintains the currently active banner
///   </li>
///   <li>
///     handles attaching/detaching the banner view from a container
///   </li>
///   <li>
///     notifies both a delegate and the container about lifecycle events
///   </li>
/// </ul>
/// This class is intended to be the core building block for banner presentation logic.
SWIFT_CLASS("_TtC8Playwire17PWAdViewPresenter")
@interface PWAdViewPresenter : NSObject
/// Delegate que será notificado cuando cambie el banner actual.
@property (nonatomic, weak) id <PMAdViewPresenterDelegate> _Nullable delegate;
/// Convenience initializer that builds a banner loader internally.
/// \param adUnitName The ad unit identifier.
///
/// \param controller The view controller used for ad loading context.
///
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nonnull)controller;
/// Initializes the presenter with a preconfigured banner loader.
/// Automatically starts loading a banner. Each load result updates
/// the internal state and presentation.
/// \param bannerLoader The loader used to fetch banners.
///
- (nonnull instancetype)initWithBannerLoader:(PMBannerAdLoader * _Nonnull)bannerLoader OBJC_DESIGNATED_INITIALIZER;
/// The view that will host the banner.
/// When changed, the presenter automatically moves the banner view
/// between containers and triggers lifecycle callbacks.
/// If both old and new holders are non-nil, a context change is triggered.
@property (nonatomic, strong) UIView * _Nullable bannerHolder;
/// Cleans up the current banner and releases resources.
/// This:
/// <ul>
///   <li>
///     calls <code>cleanup()</code> on the banner
///   </li>
///   <li>
///     removes it from the container
///   </li>
///   <li>
///     clears internal references
///   </li>
/// </ul>
- (void)cleanup;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class PWTargeting;
@protocol PWFullScreenAdDelegate;
@class PWLoadParams;
SWIFT_CLASS("_TtC8Playwire14PWFullScreenAd")
@interface PWFullScreenAd : NSObject
@property (nonatomic, strong) PWTargeting * _Nonnull targeting;
@property (nonatomic, readonly) BOOL isLoaded;
@property (nonatomic, weak) id <PWFullScreenAdDelegate> _Nullable delegate;
- (void)load;
- (void)loadWithParams:(PWLoadParams * _Nonnull)params;
- (void)show;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC8Playwire11PWAppOpenAd")
@interface PWAppOpenAd : PWFullScreenAd
@property (nonatomic) BOOL autoReloadOnExpiration;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName viewController:(UIViewController * _Nonnull)viewController delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)show;
@end

@protocol PWViewAdDelegate;
@class NSCoder;
SWIFT_CLASS("_TtC8Playwire8PWViewAd")
@interface PWViewAd : UIView
@property (nonatomic, copy) NSString * _Nullable adUnitName;
@property (nonatomic) BOOL autoload;
@property (nonatomic, weak) id <PWViewAdDelegate> _Nullable delegate;
@property (nonatomic, readonly, strong) PWTargeting * _Nonnull targeting;
@property (nonatomic, weak) UIViewController * _Nullable viewController;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName delegate:(id <PWViewAdDelegate> _Nullable)delegate;
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName controller:(UIViewController * _Nullable)controller;
- (void)awakeFromNib;
- (void)destroy;
- (void)load;
- (void)loadWithParams:(PWLoadParams * _Nonnull)params;
@property (nonatomic, readonly) BOOL isLoaded;
- (void)refresh;
@end

SWIFT_CLASS("_TtC8Playwire12PWBannerView")
@interface PWBannerView : PWViewAd
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class GADAdLoader;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
@end

@class GADNativeAd;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
@end

@class NSValue;
@class GAMBannerView;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GAMBannerAdLoaderDelegate>
- (NSArray<NSValue *> * _Nonnull)validBannerSizesForAdLoader:(GADAdLoader * _Nonnull)adLoader SWIFT_WARN_UNUSED_RESULT;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveGAMBannerView:(GAMBannerView * _Nonnull)bannerView;
@end

@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADNativeAdDelegate>
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdIsMuted:(GADNativeAd * _Nonnull)nativeAd;
@end

@class GADBannerView;
@interface PWBannerView (SWIFT_EXTENSION(Playwire)) <GADBannerViewDelegate>
- (void)bannerViewDidReceiveAd:(GADBannerView * _Nonnull)bannerView;
- (void)bannerView:(GADBannerView * _Nonnull)bannerView didFailToReceiveAdWithError:(NSError * _Nonnull)error;
- (void)bannerViewDidRecordImpression:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidRecordClick:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillPresentScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewWillDismissScreen:(GADBannerView * _Nonnull)bannerView;
- (void)bannerViewDidDismissScreen:(GADBannerView * _Nonnull)bannerView;
@end

typedef SWIFT_ENUM(NSInteger, PWCMPType, open) {
  PWCMPTypeNone = 0,
  PWCMPTypeAlreadyLaunched = 1,
  PWCMPTypeGoogleUmp = 2,
};

@protocol PWFloatingBannerAnimationHandler;
@class PWFloatingView;
SWIFT_CLASS("_TtC8Playwire16PWFloatingBanner")
@interface PWFloatingBanner : NSObject <PMAdViewPresenterDelegate>
@property (nonatomic, weak) id <PWFloatingBannerAnimationHandler> _Nullable animationHandler;
@property (nonatomic) enum FloatingViewCorner preferredCorner;
@property (nonatomic, strong) UIView * _Nullable inlineView;
- (nonnull instancetype)initWithPresenter:(PWAdViewPresenter * _Nonnull)presenter floatingView:(PWFloatingView * _Nonnull)floatingView OBJC_DESIGNATED_INITIALIZER;
- (void)didChangeAdPresenterBannerWithPresenter:(PWAdViewPresenter * _Nonnull)presenter oldBanner:(id <PMBannerAd> _Nullable)oldBanner newBanner:(id <PMBannerAd> _Nullable)newBanner;
- (void)cleanup;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_PROTOCOL("_TtP8Playwire32PWFloatingBannerAnimationHandler_")
@protocol PWFloatingBannerAnimationHandler
- (void)performAnimationWithBlock:(void (^ _Nonnull)(void))block completion:(void (^ _Nullable)(void))completion;
@end

@class UIGestureRecognizer;
/// A draggable floating view that can snap to predefined screen corners.
/// <code>PWFloatingView</code> is designed to be superimposed on top of a view controller’s
/// view and supports two main layout modes:
/// <ul>
///   <li>
///     <em>Cornered mode</em>: the view is positioned in one of the screen corners and can be dragged.
///   </li>
///   <li>
///     <em>Superimposed mode</em>: the view fills a target view and dragging is disabled.
///   </li>
/// </ul>
/// When dragging ends, the view automatically snaps to the nearest corner.
/// The view respects safe area insets and configurable margins when computing
/// valid positions.
SWIFT_CLASS("_TtC8Playwire14PWFloatingView")
@interface PWFloatingView : UIView <UIGestureRecognizerDelegate>
/// Margins applied when positioning the view in cornered mode.
@property (nonatomic) UIEdgeInsets corneredMargins;
/// Size used when the view is in cornered mode.
@property (nonatomic) CGSize corneredSize;
/// Not supported. Must be initialized programmatically.
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
/// Initializes a floating view attached to a view controller.
/// During initialization:
/// <ul>
///   <li>
///     the view is added to the controller’s root view
///   </li>
///   <li>
///     a pan gesture recognizer is configured
///   </li>
///   <li>
///     an initial layout reset is performed
///   </li>
/// </ul>
/// \param controller The view controller that will host the floating view.
///
- (nonnull instancetype)initWithController:(UIViewController * _Nonnull)controller OBJC_DESIGNATED_INITIALIZER;
/// Allows simultaneous recognition with other gestures.
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer * _Nonnull)otherGestureRecognizer SWIFT_WARN_UNUSED_RESULT;
/// Expands the view to match the frame of a target view.
/// Disables dragging behavior.
/// \param targetView The view to overlay.
///
- (void)layoutSuperimposedTo:(UIView * _Nonnull)targetView;
/// Positions the view in the default corner (<code>.bottomRight</code>).
- (void)layoutCornered;
/// Positions the view in the default corner (<code>.bottomRight</code>).
- (void)resetLayout;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_PROTOCOL("_TtP8Playwire22PWFullScreenAdDelegate_")
@protocol PWFullScreenAdDelegate
- (void)fullScreenAdDidLoad:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidFailToLoad:(PWFullScreenAd * _Nonnull)ad error:(PWAdError * _Nonnull)error;
- (void)fullScreenAdWillPresentFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdWillDismissFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidDismissFullScreenContent:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidFailToPresentFullScreenContent:(PWFullScreenAd * _Nonnull)ad error:(PWAdError * _Nonnull)error;
- (void)fullScreenAdDidRecordImpression:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidRecordClick:(PWFullScreenAd * _Nonnull)ad;
- (void)fullScreenAdDidUserEarn:(PWFullScreenAd * _Nonnull)ad type:(NSString * _Nonnull)type amount:(double)amount;
@end

SWIFT_CLASS("_TtC8Playwire14PWInterstitial")
@interface PWInterstitial : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName viewController:(UIViewController * _Nonnull)viewController delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)show;
@end

@interface PWInterstitial (SWIFT_EXTENSION(Playwire)) <PMInterstitialAdDelegate>
- (void)adImpressedWithAd:(id <PMAd> _Nonnull)ad;
- (void)adClickedWithAd:(id <PMAd> _Nonnull)ad;
- (void)fullScreenAdClosedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
- (void)fullScreenAdWillCloseWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
- (void)fullScreeenAdPresentedWithFullScreen:(id <PMFullScreenAd> _Nonnull)fullScreen;
@end

SWIFT_CLASS("_TtC8Playwire12PWLoadParams")
@interface PWLoadParams : NSObject
- (PWLoadParams * _Nonnull)withTargeting:(NSDictionary<NSString *, NSString *> * _Nonnull)targeting;
- (PWLoadParams * _Nonnull)withWidth:(CGFloat)width;
- (PWLoadParams * _Nonnull)withDeviceOrientation:(UIInterfaceOrientation)orientation;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC8Playwire12PWNativeView")
@interface PWNativeView : PWViewAd
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface PWNativeView (SWIFT_EXTENSION(Playwire)) <GADNativeAdLoaderDelegate>
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didReceiveNativeAd:(GADNativeAd * _Nonnull)nativeAd;
- (void)adLoader:(GADAdLoader * _Nonnull)adLoader didFailToReceiveAdWithError:(NSError * _Nonnull)error;
@end

@interface PWNativeView (SWIFT_EXTENSION(Playwire)) <GADNativeAdDelegate>
- (void)nativeAdDidRecordImpression:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidRecordClick:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillPresentScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdWillDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdDidDismissScreen:(GADNativeAd * _Nonnull)nativeAd;
- (void)nativeAdIsMuted:(GADNativeAd * _Nonnull)nativeAd;
@end

SWIFT_CLASS("_TtC8Playwire10PWRewarded")
@interface PWRewarded : PWFullScreenAd
- (nonnull instancetype)initWithAdUnitName:(NSString * _Nonnull)adUnitName viewController:(UIViewController * _Nonnull)viewController delegate:(id <PWFullScreenAdDelegate> _Nullable)delegate;
- (void)show;
@end

SWIFT_CLASS("_TtC8Playwire11PWTargeting")
@interface PWTargeting : NSObject
- (PWTargeting * _Nonnull)clear SWIFT_WARN_UNUSED_RESULT;
- (PWTargeting * _Nonnull)add:(NSDictionary<NSString *, NSString *> * _Nullable)targets;
- (PWTargeting * _Nonnull)remove:(NSArray<NSString *> * _Nullable)keys;
- (PWTargeting * _Nonnull)setClientTag:(NSString * _Nonnull)clientTag at:(NSInteger)index;
- (PWTargeting * _Nonnull)removeClientTagAt:(NSInteger)index;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP8Playwire16PWViewAdDelegate_")
@protocol PWViewAdDelegate
- (void)viewAdDidLoad:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidFailToLoad:(PWViewAd * _Nonnull)ad error:(PWAdError * _Nonnull)error;
- (void)viewAdWillPresentFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdWillDismissFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidDismissFullScreenContent:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidRecordImpression:(PWViewAd * _Nonnull)ad;
- (void)viewAdDidRecordClick:(PWViewAd * _Nonnull)ad;
@end

@class GAMRequest;
SWIFT_CLASS("_TtC8Playwire11PlaywireSDK")
@interface PlaywireSDK : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) PlaywireSDK * _Nonnull shared;)
+ (PlaywireSDK * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) enum LogLevel logLevel;
@property (nonatomic, readonly, strong) PWTargeting * _Nonnull targeting;
@property (nonatomic) BOOL test;
@property (nonatomic) enum PWCMPType cmp;
- (void)startWithPublisherId:(NSString * _Nonnull)publisherId appId:(NSString * _Nonnull)appId viewController:(UIViewController * _Nonnull)viewController completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
- (void)initializeWithPublisherId:(NSString * _Nonnull)publisherId appId:(NSString * _Nonnull)appId viewController:(UIViewController * _Nonnull)viewController completionHandler:(void (^ _Nonnull)(void))completionHandler SWIFT_DEPRECATED_MSG("This method silently fails on error. Please migrate to 'start' to properly handle SDK initialization failures.");
@property (nonatomic) BOOL isMuted;
- (void)configureWithRequest:(GAMRequest * _Nonnull)request;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
